# Generated by Django 4.2.3 on 2023-10-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaPEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_registro_pep', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=20)),
                ('persona_pep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='personas.personapep')),
            ],
        ),
    ]
