# Generated by Django 4.2.3 on 2023-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personapep',
            name='cuentas_extranjeras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personapep',
            name='es_pep',
            field=models.CharField(default='Si', max_length=50),
        ),
    ]
